### ISSUE TITLE
MapProxy basic setup

### ISSUE THREAD

**Issue by ChameleonScales** [domlysz/BlenderGIS#205]
I made a basic proxy map using mapproxy and this [setup file](https://pastebin.com/mmcJmXrR), which I launch (and you can too) with the command `mapproxy-util serve-develop config-pratique.yaml`
It works fine on QGIS using the following URL to connect to it:
http://127.0.0.1:8080/wmts/1.0.0/WMTSCapabilities.xml
A single tile has this URL structure:
http://127.0.0.1:8080/wmts/photographiesaeriennes/ign_grid/02/2/3.png

I tried for a while to get the right code in servicesDefs.py to make it work in BlenderGIS, to no avail.

Is it even possible ?

**Comment by domlysz** [comment]
yes it can work, the only tricky step is to correctly setup the grid accordingly with the one served by mapproxy, but it can be very easy with common grids

As I can see you want to serve a map with Web Mercator projection and there is a well know grid for this projection (the Google one) whitch is already predefined both in BlenderGIS and [Mapproxy](https://mapproxy.org/docs/1.11.0/configuration.html#id6).

In Mapproxy you just need to base your source and cache on GLOBAL_WEBMERCATOR predefined grid.

Another important point is that BlenderGIS is only abble to fetch WMTS url following KVP standard,  but for now your url follow the REST standard. This parameter can be setup in mapproxy :

```
services: 
  wmts:
    kvp: true
    restful: false

sources:
  ign_source:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: ...

caches:
  ign_cache:
    sources: [ign_source]
    grids: [GLOBAL_WEBMERCATOR]

layers:
- name: photographiesaeriennes
  sources: [ign_cache]
```

Then in BlenderGIS create a new source based on "WM" grid (already defined), and ign_cache for the matrix name as defined in MapProxy

	"IGN_PROXY" : {
		"name" : 'IGN proxy orthophotos',
		"description" : 'IGN proxy orthophoto',
		"service": 'WMTS',
		"grid": 'WM',
		"matrix" : 'ign_cache',
		"layers" : {
			"ORTHO" : {"urlKey" : 'photographiesaeriennes', "name" : 'Orthophotos', "description" : '',
				"format" : 'jpeg', "style" : 'normal', "zmin" : 0, "zmax" : 22},
		},
		"urlTemplate": {
			"BASE_URL" : 'url_to_mapproxyWSGI.py_or_alias/service?',
			"SERVICE" : 'WMTS',
			"VERSION" : '1.0.0',
			"REQUEST" : 'GetTile',
			"LAYER" : '{LAY}',
			"STYLE" : '{STYLE}',
			"FORMAT" : 'image/{FORMAT}',
			"TILEMATRIXSET" : '{MATRIX}',
			"TILEMATRIX" : '{Z}',
			"TILEROW" : '{Y}',
			"TILECOL" : '{X}'
			},
		"referer": ""
	},

also, remember BlenderGIS has it own cache so using mapproxy, your data will be cached twice ! Futhermore BlenderGIS will update a tile only if there is older than 90 days, this is hardcoded in https://github.com/domlysz/BlenderGIS/blob/master/core/basemaps/gpkg.py
